# Repository
repo_name: Nutrition
repo_url: https://github.com/Maggie-87/Nutrition
edit_uri: ""

site_name: Documentation
site_description: 
site_author: 
site_url: https://maggie-87.github.io/Nutrition/
site_dir: site

theme: 
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  # palette:
  #   - scheme: default
  #     primary: white
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: cyan
  #     accent: cyan
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  favicon: image/favicon.ico

# Plugins
plugins:
  - search
  - include-markdown

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - admonition

nav:
  - Home: index.md
  - Food: food.md
  - Body: body.md